### ISSUE TITLE
problem to buld with GCC 15.1.0

### ISSUE THREAD

**Issue by filochard** [rgleason/celestial_navigation_pi#174]
Hi Rick

I have resolved the problem to build quite all the plugins with GCC 15.1.0 by adding a line in opencpn-libs/api-18/ocpn_plugin.h : 
#include `<cstdint>`

After the discussion inside https://github.com/OpenCPN/opencpn-libs/issues/21 , Alec has added this line for API-20 so building plugins for the next version of OpenCPN will be easy even with GCC 15 (this addition is nevertheless backward compatible) [commit 724961a](https://github.com/OpenCPN/OpenCPN/commit/724961a2c427ee9dc70c98705d06c691a88decb7)

celestial_navigation_pi  is the only plugin that I can't build with GCC 15 which is very strict for the formulas (more than previous GCC 13 or GCC 14)

Something is missing inside /src/geomag.c   (inside lines 176 to 183)  Have a look at this attached file : 

[what-to-do.txt](https://github.com/user-attachments/files/19949116/what-to-do.txt)

The changes brought to these lines will make it ready for the future GCC 15 but won't hurt for the actual versions of GCC

**Comment by filochard** [comment]
Maybe ask to Sebastien Rousset who seems to master well GCC !

**Comment by stelian42** [comment]
Does this help ? https://github.com/rgleason/celestial_navigation_pi/commit/4db21637360a2617599f3227d7419e0a67c4d546

**Comment by filochard** [comment]
Hi Stelian
That did the trick
This plugin is now already OK for future build with GCC 15 (more strict for the syntax !)
Congratulations

**Comment by rgleason** [comment]
Thanks Stelian.   

Also Leamas suggests

> This is actually easily fixed in any plugin running into this error by doing #include <cstdint> before #include "ocpn_plugin.h". Not that complicated so to speak.

See Leamas Summary here - Not an issue for us for quite some time.
https://github.com/OpenCPN/OpenCPN/issues/4503#issuecomment-2837694954

**Comment by filochard** [comment]
Hi Rick and Stelian

The changes brought by Stelian are backward compatible with GCC 12.3 : 
I can always build with GCC 12.3
but better : I can now build with GCC 15.1.0
(I am apparently the only one who can test a build with GCC 15 that is not yet spread over lots of Linux distributions)

Nota Bene
celestial_navigation_pi was the only plugin that couldn't build with only one patch for ocpn-plugin.h in opencpn-libs/api-18/
and which needed a specific adaptation
I think that this last commit is worth keeping it 

By the way the improve branch should be merged to master and eventually tagged (I have used a git clone of the last commit to build it)

**Comment by filochard** [comment]
This issue may be closed as resolved
Unless it might be known by Alec

**Comment by rgleason** [comment]
@filochard 

I read somewhere, I think it was bdbcat, that we could put the include in the CMakeLists.txt file.
Do you know where that would be appropriately located in that file?

#include <cstdint>

**Comment by filochard** [comment]
Hi Rick
Indeed Alec has already added #include  `<cstdint>` inside opencpn-libs/api-20/ocpn_plugin.h for the next version of OpenCPN, 
to allow build of the plugins with GCC 15.1.0 see : 
https://github.com/OpenCPN/opencpn-libs/commit/d21e80a825a0764d3b72fda0928a7a660226d5fa
When the next OpenCPN will be out there will be no problem to build plugins whatever GCC version is used 

But for coherency with the code of OpenCPN 5.10.2 he can't add this line for  opencpn-libs/api-18/ocpn_plugin.h 

Now, the plugins for OpenCPN 10.2 can't be built  with GCC 15.1.0 but that's not an emergency
They will in the future with the next version of OpenCPN

The only plugin for which adding  #include  `<cstdint>` inside opencpn-libs/api-18/ocpn_plugin.h was not enough is : 
 Celestial-Navigation
That's what I have discovered when I tried to build it and why I rang the bell in this particular issue

Now that stelian has corrected the code of geomag.c  There won't be any failure for the next OpenCPN if it is built with GCC 15.1.0

Besides this to build the other plugins I have had to create different patches for each different versions of opencpn-libs versions used for each of them 
(since the plugins are linked to different commits of opencpn-libs : c1d8263 ,  a001083 , facd6f6 , 9804fbe , 1a6c1a7 or 3d56fe8 )

It would have been simpler if all the plugins used the same commit version of opencpn-libs

Besides of the plugins problem that is solved for me 
I'm still stuck for OpenCPN 5.10.2 itself that we will not be able to provide for the next version of our distribution 
based on GCC 15.1.0  (too much lines to change for too much part of its code) unless we force the build as if it was a previous version of GCC 
(forcing to use -std=gnu17 instead of -std= gnu23 :  that will workaround the syntax approximations, not accepted by GCC 15.1 now, but tolerated  by its previous versions)

**Comment by stelian42** [comment]
If I understand correctly, the issue is now fixed as far as Celestial Navigation Plugin is concerned, right ?

**Comment by rgleason** [comment]
Yes, I believe so,but Filochard will reply.   I also think he wants all plugins to use the most current version of opencpn-libs, but I will not be doing a total update of all 20 odd plugins for another three months.

**Comment by rgleason** [comment]
Can this be closed now? Filochard?

**Comment by filochard** [comment]
Hi Rick 
I'm sorry for my late answer : I have been far from home and from internet for a week
It's OK now for Celestial Navigation : it builds correctly with GCC 15.1.0

(the problem remains with opencpn-libs that I need to patch for OpenCPN 5.10.2 
(adding one line :  `#include <cstdint>` inside opencpn-libs/api-18/ocpn_plugin.h)
but this has already been corrected for the next version of OpenCPN : 
in opencpn-libs/api-20/ocpn_plugin.h   this line has been added....

And for OpenCPN itself  `#include <cstdint>` has been added where needed 
(Thanks to Alec and Nohal)
